### ISSUE TITLE
Problems importing modded skins? 

### ISSUE THREAD

**Issue by ramsay6** [RQWorldblender/io_scene_numdlb#1]
I'm trying to import modded skins (.numdlb format) downloaded from GameBanana for smash ultimate, I've tested a couple dozen and only a few have worked and imported for me. I'll post a screenshot of the blender error I get. I've tested the models on 2.83 LTS and 3.41. All the regular smash ultimate fighters and animations work for me. Wondering what I need to do to make these modded skins work in blender. Any help is greatly appreciated thanks! 

Here is a link to the specific models im trying to get working:
https://gamebanana.com/mods/362715

<img width="1016" alt="Screen Shot 2023-02-17 at 12 03 46 PM" src="https://user-images.githubusercontent.com/125686775/219718187-06de91b3-f58a-46ef-9017-8fcaf71f6f5b.png">

**Comment by RQWorldblender** [comment]
Maybe I should've made it more clear, but this add-on doesn't explicitly
support mods yet, only the official models as ripped from the original
game(s). I'm not as well-versed with mods for console video games due to
their often proprietary nature, which at this point would be more likely to
recommend using open file formats. I do know about open-source libraries
being used in more of these video games, but they're not of much use when
trying to reverse engineer undocumented formats. It's quite similar to the
situation between OOXML (default Microsoft Office format since 2007) and
ODF (Open Document Format used in LibreOffice and compatible), except that
it's possible that I have no documentation to begin with (unless a game is
using a premade engine, such as Godot, Unity, or Unreal).

However, if you can tell me how these mods are created and their structure,
maybe I can work something out.

**Comment by ramsay6** [comment]
I'm not sure how they're created or their structure, but I sent a link to the skins if you wanna check them out. I've gotten some other mod skins to work so it definitely is possible. The blender errors I get are probably the key to fixing the problem but Im not sure what they mean. Alternatively, is there another method for adding nuanmb animations to numdlb models?

**Comment by RQWorldblender** [comment]
Let me think, I think some of these mod skins are simply replacement models that may not even have an armature, according to the error you're getting. I think the code to check for the armature can be disabled on a temporary basis, but I never seen any of the original game models ever go without an armature.

I'm just telling you what can be done; by this point, ever since Super Smash Bros. Ultimate stopped receiving DLC since October 2021, I mostly moved on to playing other Nintendo-published games (and more PC games in the near future), hence I won't be of as much help as from before.

**Comment by ramsay6** [comment]
It seems your correct! after importing the original samus model, I can  import the mod skin. Not sure how to properly import the skin on to the rig though? 

![2023-02-17 13_54_30-Greenshot](https://user-images.githubusercontent.com/125686775/219762899-8ec64d78-4322-4ca6-9856-22ff7534132d.png)
![2023-02-17 14_02_17-Greenshot](https://user-images.githubusercontent.com/125686775/219762929-d9857095-eae8-46ef-8cc2-da905d657c90.png)

**Comment by RQWorldblender** [comment]
Oh yeah, I see that you got your mod to import. Though you need to have the model rotated 90 degrees on the X-axis, and then bind the models to the armature, by making their parent their armature and applying the armature modifier to them.

**Comment by ramsay6** [comment]
It works thanks so much!

**Comment by RQWorldblender** [comment]
After that, is there something else or other issue that you ran into?

**Comment by ramsay6** [comment]
Yeah actually, some characters with face seams it makes the seam more noticeable and makes their different face parts look kind of different. 
![2023-02-17 17_02_30-Greenshot](https://user-images.githubusercontent.com/125686775/219803564-30b1f6d2-11ee-4d75-8492-8530ebfc12e9.png)

Also with a lot of characters there seems to be some sort of line usually in the middle of the model (see on links nose). 
And it looks like soras hair gets completely ruined when adding animation. Similar things with  some other characters 

![2023-02-17 17_02_30-Greenshot](https://user-images.githubusercontent.com/125686775/219803564-30b1f6d2-11ee-4d75-8492-8530ebfc12e9.png)

![2023-02-17 17_06_13-Greenshot](https://user-images.githubusercontent.com/125686775/219803596-ec6bc48f-f7fa-4229-868a-9acb16aa62c5.png)

**Comment by RQWorldblender** [comment]
Let me see what you're trying to do. Those seams can appear if different shaders are used. I don't have access to the shaders the original game uses, hence it may not be possible to fully replicate the looks 1:1.

About the hairs getting messed up, I was hearing from someone else that the bones are point-based, not head-tail based that Blender uses, so it is possible that stuff like bone rolls are not translated correctly. This is the kind of stuff that would make me prefer to work with games using 3rd-party engines, as what I learn from them can be applied to multiple games.

**Comment by ramsay6** [comment]
Im trying to export the animations as fbx and use them in another program to make animated videos but I think the solution is to export the characters from blender with rig, then re link that rig to a regular smash ultimate model of that character to fix the face seam, texture, polygon issues. Ill try it. and for sora I think I can just export the animations then delete all keyframes on his hair and reset the values then animate the hair manually. might work out

**Comment by RQWorldblender** [comment]
Ah, now that you've given your situation, I actually have to say that I've been wanting to learn more about 3D animation, as the best animation I can do is not enough to make a character do a walk cycle (how embarrassing for me!). Where have you been learning all that stuff from, I wonder?

I feel that armatures have nothing to do with how meshes are rendered. You should switch to the material view instead of solid view, as that will give you better results, especially letting you see properly most of the characters' eyes. I'm now using Blender 2.93 LTS, but I will eventually upgrade to a more recent LTS version.

Perhaps if you can complete the videos, can I see the final product?

**Comment by ramsay6** [comment]
I started to learn animation from just watching youtube videos, but mainly practice it is tough but after a while one day you make up and now how to do it. I dont use blender I use cinema4d which is a good program but blender is also fantastic. I would just start to playing around with things and youll get a feel of it. Honestly you dont need to know how to animate to start making some videos though, you could just use the smash animations to make some videos, as well as theres a site called mixamo.com that allows you to add mocap animations to pretty much any character which is a good place to start.
And yeah forsure my youtube is Napkins X www.youtube.com/@NapkinsX
Im still playing around with the smash animations so I havent posted any videos with them yet but I should be posting a Metroid video next week using the smash animations, and some smash videos later on
